name: Android Build

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK and AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install NPM Dependencies
        run: npm install

      - name: Generate App Assets
        run: |
          npm install @capacitor/assets
          npx @capacitor/assets generate --android



      - name: Sync Capacitor Android
        run: npx cap sync android

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Make Gradle Executable
        run: chmod +x ./android/gradlew

      - name: Build Debug APK
        working-directory: ./android
        run: ./gradlew assembleDebug

      - name: Build Release AAB
        working-directory: ./android
        run: ./gradlew bundleRelease

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/**/*.apk

      - name: Upload Release AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/**/*.aab
